/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodoImport } from './routes/todo'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as TodoNewImport } from './routes/todo.new'
import { Route as TodoIdImport } from './routes/todo.$id'
import { Route as AuthInvoicesImport } from './routes/_auth.invoices'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthInvoicesIndexImport } from './routes/_auth.invoices.index'
import { Route as AuthInvoicesInvoiceIdImport } from './routes/_auth.invoices.$invoiceId'

// Create/Update Routes

const TodoRoute = TodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodoNewRoute = TodoNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TodoRoute,
} as any)

const TodoIdRoute = TodoIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TodoRoute,
} as any)

const AuthInvoicesRoute = AuthInvoicesImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthInvoicesIndexRoute = AuthInvoicesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInvoicesRoute,
} as any)

const AuthInvoicesInvoiceIdRoute = AuthInvoicesInvoiceIdImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AuthInvoicesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesImport
      parentRoute: typeof AuthImport
    }
    '/todo/$id': {
      id: '/todo/$id'
      path: '/$id'
      fullPath: '/todo/$id'
      preLoaderRoute: typeof TodoIdImport
      parentRoute: typeof TodoImport
    }
    '/todo/new': {
      id: '/todo/new'
      path: '/new'
      fullPath: '/todo/new'
      preLoaderRoute: typeof TodoNewImport
      parentRoute: typeof TodoImport
    }
    '/_auth/invoices/$invoiceId': {
      id: '/_auth/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthInvoicesInvoiceIdImport
      parentRoute: typeof AuthInvoicesImport
    }
    '/_auth/invoices/': {
      id: '/_auth/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthInvoicesIndexImport
      parentRoute: typeof AuthInvoicesImport
    }
  }
}

// Create and export the route tree

interface AuthInvoicesRouteChildren {
  AuthInvoicesInvoiceIdRoute: typeof AuthInvoicesInvoiceIdRoute
  AuthInvoicesIndexRoute: typeof AuthInvoicesIndexRoute
}

const AuthInvoicesRouteChildren: AuthInvoicesRouteChildren = {
  AuthInvoicesInvoiceIdRoute: AuthInvoicesInvoiceIdRoute,
  AuthInvoicesIndexRoute: AuthInvoicesIndexRoute,
}

const AuthInvoicesRouteWithChildren = AuthInvoicesRoute._addFileChildren(
  AuthInvoicesRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInvoicesRoute: typeof AuthInvoicesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInvoicesRoute: AuthInvoicesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TodoRouteChildren {
  TodoIdRoute: typeof TodoIdRoute
  TodoNewRoute: typeof TodoNewRoute
}

const TodoRouteChildren: TodoRouteChildren = {
  TodoIdRoute: TodoIdRoute,
  TodoNewRoute: TodoNewRoute,
}

const TodoRouteWithChildren = TodoRoute._addFileChildren(TodoRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/todo': typeof TodoRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/invoices': typeof AuthInvoicesRouteWithChildren
  '/todo/$id': typeof TodoIdRoute
  '/todo/new': typeof TodoNewRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices/': typeof AuthInvoicesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/todo': typeof TodoRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/todo/$id': typeof TodoIdRoute
  '/todo/new': typeof TodoNewRoute
  '/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/invoices': typeof AuthInvoicesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/todo': typeof TodoRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/invoices': typeof AuthInvoicesRouteWithChildren
  '/todo/$id': typeof TodoIdRoute
  '/todo/new': typeof TodoNewRoute
  '/_auth/invoices/$invoiceId': typeof AuthInvoicesInvoiceIdRoute
  '/_auth/invoices/': typeof AuthInvoicesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/todo'
    | '/dashboard'
    | '/invoices'
    | '/todo/$id'
    | '/todo/new'
    | '/invoices/$invoiceId'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/todo'
    | '/dashboard'
    | '/todo/$id'
    | '/todo/new'
    | '/invoices/$invoiceId'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/todo'
    | '/_auth/dashboard'
    | '/_auth/invoices'
    | '/todo/$id'
    | '/todo/new'
    | '/_auth/invoices/$invoiceId'
    | '/_auth/invoices/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TodoRoute: typeof TodoRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TodoRoute: TodoRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/todo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/invoices"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/todo": {
      "filePath": "todo.tsx",
      "children": [
        "/todo/$id",
        "/todo/new"
      ]
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/invoices": {
      "filePath": "_auth.invoices.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/invoices/$invoiceId",
        "/_auth/invoices/"
      ]
    },
    "/todo/$id": {
      "filePath": "todo.$id.tsx",
      "parent": "/todo"
    },
    "/todo/new": {
      "filePath": "todo.new.tsx",
      "parent": "/todo"
    },
    "/_auth/invoices/$invoiceId": {
      "filePath": "_auth.invoices.$invoiceId.tsx",
      "parent": "/_auth/invoices"
    },
    "/_auth/invoices/": {
      "filePath": "_auth.invoices.index.tsx",
      "parent": "/_auth/invoices"
    }
  }
}
ROUTE_MANIFEST_END */
